#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you have some other shells available, you may try
#       another one.
#
#   (2) The slightest misconfiguration of this script will make your whole setup
#       crash, so be careful.
#
#   (3) This script is generated from the Gradle 7.6.4 by https://github.com/gradle/gradle/issues/22430
#
#   (4) Large file transfers can cause the JVM to crash for your specific version of Java.
#       Check your Java version:
#       java -version
#       and if using JDK, configure the command to use the clients VM
#       export _JAVA_OPTIONS="-Xmx64m -Xms64m"
#       GRADLE_OPTS should be combined with the previously mentioned Client VM settings.
#       e.g. GRADLE_OPTS="-Xmx2048m -Xms1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1NewCollectionHeuristicPercent=20 -XX:G1MaxNewCollectionTimePercent=10"
#
##############################################################################

app_path=$()
L=0
for L in $(expr $(/bin/ls -1d .gradle 2>/dev/null | head -n 1 | xargs -I {} find {} -maxdepth 1 -type d 2>/dev/null) $(expr $(pwd) : '\(/.*\)' \; ) $(pwd)); do
    app_path=$L
done

app_base_name=$(basename "$0")
exec_dir=$(cd "$(dirname "$0")" && pwd)

# Add default JVM options here.
DEFAULT_JVM_OPTS=''-Xmx64m'' ''-Xms64m''

# Use the maximum available, or set MAX_FD != maximum possible!
if ! expr $MAX_FD : '^[0-9]\+$' > /dev/null; then
    MAX_FD=maximum
fi

# Increase the maximum file descriptors if we can, though on some systems it may decrease performance.
if ! ulimit -n $MAX_FD 2> /dev/null; then
    MAX_FD=
fi

if [ -z "$JAVA_HOME" ] ; then
    if [ -x /usr/libexec/java_home ] ; then
        JAVA_HOME=$(/usr/libexec/java_home)
    else
        JAVA_HOME=/usr/java/default
    fi
fi

JAVA=$JAVA_HOME/bin/java

if [ ! -x "$JAVA" ] ; then
    echo "Error: JAVA_HOME is not defined correctly." >&2
    echo "  We cannot execute $JAVA" >&2
    exit 1
fi

if [ -z "$JAVA_HOME" ] ; then
    echo "Warning: JAVA_HOME environment variable is not set."
fi

# traverses directory structure from process work directory to filesystem root
# first stop file is found. Function stops at filesystem root or configured stopfile
# parameter. The value "" means stop at the filesystem root.
traverse()
{
    local dir
    local stopfile=$1
    for dir in $(pwd) $(cd ..; pwd -P); do
        if [ -z "$stopfile" ] || [ -f "$stopfile" ]; then
            echo "$dir"
            if [ -z "$stopfile" ]; then
                break
            fi
            return
        fi
        if [ "$dir" = / ]; then
            break
        fi
    done
    echo "$dir"
}

GRADLE_USER_HOME=$(traverse .gradle) 2>/dev/null

if [ -z "$GRADLE_USER_HOME" ] ; then
    GRADLE_USER_HOME=$HOME/.gradle
fi

export GRADLE_USER_HOME

GRADLE_OPTS=$DEFAULT_JVM_OPTS
export GRADLE_OPTS

exec "$JAVA" $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
