#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ]; do
    ls=$( ls -ld "$PRG" )
    link=$( expr "$ls" : '.*-> \(.*\)$' )
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$( dirname "$PRG" )"/$link"
    fi
done
SAVED="$(cd "$(dirname "$PRG")" && pwd)"
APP_HOME="$SAVED"
APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# For Cygwin or MSYS, switch paths to Windows format before running java
case "$( uname )" in
  CYGWIN* )
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --mixed "$JAVACMD" )
    ;;
esac

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...settings.gradle Gradle will override any value you set with the defaults.
#   * and any _JAVA_OPTIONS environment variables
for arg do
    case $arg in
      -*)   false;;
      /?*)  
        arg=$( cygpath --path --mixed "$arg" )
        ;;
    esac
    args="$args $arg"
done

if [ -z "$JAVA_HOME" ]; then
    JAVACMD="java"
else
    JAVACMD="$JAVA_HOME/bin/java"
fi

exec "$JAVACMD" \
  $DEFAULT_JVM_OPTS \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  -Dorg.gradle.appname="$APP_BASE_NAME" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
