#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you have some other shells available, you may try
#       another one.
#
#   (2) The slightest misconfiguration of this script will make your whole setup
#       crash, so be careful.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while
    APP_HOME=$( cd -P "$( dirname "$PRG" )" && pwd -P )
    PRG=$( readlink "$PRG" )
    [ -n "$PRG" ]
do
    cd -P "$( dirname "$PRG" )" && pwd -P
done
APP_HOME=$( cd -P "$( dirname "$PRG" )" && pwd -P )

APP_NAME="Gradle"
APP_BASE_NAME=$( basename "$0" )

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum possible!
MAX_FD="maximum"

# Increase the maximum file descriptors if we can, though on some systems it may decrease performance.
ulimit -n "$MAX_FD" ||
    warn "Could not set maximum file descriptor limit to $MAX_FD"

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...settings.gradle Gradle will override any value you set with the defaults.
#   * and any _JAVA_OPTIONS environment variables

# For Cygwin or MSYS, switch paths to Windows format before running java
if case "$( uname )" in  #(
     CYGWIN*) true ;; #(
     MSYS* ) true ;; #(
     MINGW* ) true ;; #(
     *) false ;;
   esac then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --mixed "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        args="$args $arg"
    done
fi

exec "$JAVACMD" \
  $DEFAULT_JVM_OPTS \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  -Dorg.gradle.appname="$APP_BASE_NAME" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
